const roleKey='sourcer.prototype.roles.v1';
let savedRoles=[],editingRoleId=null;
try{const stored=JSON.parse(localStorage.getItem(roleKey)||'[]');if(Array.isArray(stored))savedRoles=stored.filter(r=>r&&typeof r.id==='string'&&typeof r.title==='string'&&typeof r.spec==='string');}catch{}
function refreshRoleSelect(){const select=document.getElementById('savedRoleSelect');select.replaceChildren(new Option('Choose a saved role',''));for(const r of savedRoles)select.add(new Option(r.title,r.id));}
function startNewRole(){editingRoleId=null;document.getElementById('roleRegistration').reset();document.getElementById('registeredRole').hidden=true;document.getElementById('roleRegistration').hidden=false;document.getElementById('registrationHeading').textContent='Register a new role';document.getElementById('registrationError').textContent='';backToRoleDetails();switchScreen('registerRole');document.getElementById('newSpec').focus();}
function backToRoleDetails(){document.getElementById('roleStepOne').hidden=false;document.getElementById('roleStepTwo').hidden=true;}
function roleValues(){return Object.fromEntries(['Spec','Title','Location','WorkType','Skills','Exclusions'].map(k=>[k.toLowerCase(),document.getElementById('new'+k).value.trim()]));}
function quoted(value){return '"'+value.replace(/["\r\n]/g,' ').trim()+'"';}
function makeQueries(r){const skills=r.skills.split(',').map(s=>s.trim()).filter(Boolean);const required=skills.map(quoted).join(' AND ');const excluded=r.exclusions.split(',').map(s=>s.trim()).filter(Boolean);const suffix=excluded.length?' NOT ('+excluded.map(quoted).join(' OR ')+')':'';return [quoted(r.title)+' AND ('+required+')'+suffix,'('+required+')'+suffix];}
document.getElementById('roleRegistration').addEventListener('submit',e=>{e.preventDefault();const r=roleValues();if(r.spec.length<30||!r.title||!r.location||!r.skills.split(',').some(x=>x.trim())){document.getElementById('registrationError').textContent='Add a specification, title, location and at least one skill.';return;}document.getElementById('registrationError').textContent='';const queries=makeQueries(r);document.getElementById('newQueryOne').value=queries[0];document.getElementById('newQueryTwo').value=queries[1];document.getElementById('newRoleSummary').textContent=r.title+' · '+r.location+' · '+r.worktype;document.getElementById('roleStepOne').hidden=true;document.getElementById('roleStepTwo').hidden=false;document.getElementById('newQueryOne').focus();});
function validQuery(q){let depth=0,quote=false;for(const c of q){if(c==='"')quote=!quote;if(!quote&&c==='(')depth++;if(!quote&&c===')'&&--depth<0)return false;}return !!q.trim()&&!quote&&depth===0;}
function saveRegisteredRole(){const q1=document.getElementById('newQueryOne').value.trim(),q2=document.getElementById('newQueryTwo').value.trim();if(!validQuery(q1)||!validQuery(q2)){document.getElementById('registrationError').textContent='Both searches need text with balanced quotes and parentheses.';return;}const role={...roleValues(),id:editingRoleId||crypto.randomUUID(),queryOne:q1,queryTwo:q2};const next=savedRoles.filter(r=>r.id!==role.id).concat(role);try{localStorage.setItem(roleKey,JSON.stringify(next));localStorage.setItem(roleKey+'.active',role.id);}catch{document.getElementById('registrationError').textContent='Browser storage is unavailable. Your role has not been saved. Keep this page open and enable browser storage.';return;}savedRoles=next;refreshRoleSelect();selectSavedRole(role.id);}
function selectSavedRole(id){const r=savedRoles.find(r=>r.id===id);if(!r)return;editingRoleId=id;document.getElementById('savedRoleSelect').value=id;document.getElementById('registrationHeading').textContent='Your registered role';document.getElementById('roleRegistration').hidden=true;document.getElementById('registeredRole').hidden=false;document.getElementById('registrationError').textContent='';for(const [target,value]of Object.entries({registeredTitle:r.title,registeredMeta:r.location+' · '+r.worktype,registeredSpec:r.spec,registeredQueryOne:r.queryOne,registeredQueryTwo:r.queryTwo}))document.getElementById(target).textContent=value;try{localStorage.setItem(roleKey+'.active',id);}catch{}switchScreen('registerRole');}
function editRegisteredRole(){const r=savedRoles.find(r=>r.id===editingRoleId);if(!r)return;for(const k of ['Spec','Title','Location','WorkType','Skills','Exclusions'])document.getElementById('new'+k).value=r[k.toLowerCase()]||'';document.getElementById('registeredRole').hidden=true;document.getElementById('roleRegistration').hidden=false;document.getElementById('newQueryOne').value=r.queryOne;document.getElementById('newQueryTwo').value=r.queryTwo;document.getElementById('newRoleSummary').textContent=r.title+' · '+r.location+' · '+r.worktype;document.getElementById('roleStepOne').hidden=true;document.getElementById('roleStepTwo').hidden=false;}
document.getElementById('specFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;if(!f.name.toLowerCase().endsWith('.txt')||f.size>1000000){document.getElementById('registrationError').textContent='Choose a .txt file under 1 MB, or paste your specification.';return;}try{document.getElementById('newSpec').value=await f.text();document.getElementById('registrationError').textContent='';}catch{document.getElementById('registrationError').textContent='Could not read this file. Paste the specification instead.';}});
refreshRoleSelect();try{selectSavedRole(localStorage.getItem(roleKey+'.active'));}catch{}
