// Consistent, browser-local prototype state; no LinkedIn operations are performed.
const samplePeople=structuredClone(candidates);
let activeRole=null,workspace={people:samplePeople,queue:[],decisions:[]},openItem=null,returnFocus=null;
const workspaceKey=()=> 'sourcer.workspace.'+(activeRole?.id||'sample');
function saveWorkspace(){try{localStorage.setItem(workspaceKey(),JSON.stringify(workspace));return true;}catch{toast('Could not save. Browser storage is unavailable.');return false;}}
function loadWorkspace(){try{workspace=JSON.parse(localStorage.getItem(workspaceKey()))||{people:activeRole?[]:structuredClone(samplePeople),queue:[],decisions:[]};}catch{workspace={people:[],queue:[],decisions:[]};toast('Saved workspace could not be read.');}renderWorkspace();}
function renderWorkspace(){candidates.splice(0,candidates.length,...workspace.people);selected=Math.max(0,Math.min(selected,candidates.length-1));remaining=candidates.length;queued=workspace.queue.length;approved=workspace.decisions.filter(d=>d.kind==='approve').length;$('#reviewCount').textContent=remaining;$('#metricReview').textContent=remaining;$('#metricApproved').textContent=approved;$('#actionCount').textContent=queued;$('#review .hero h1').textContent=activeRole?.title||'Example candidate review';$('#review .hero p').textContent=remaining+' people ready for your decision. Example results only.';$('#review .panel-head .meta').textContent=remaining+' ranked';$('#review .hero [data-screen-go="actions"]').textContent='Review '+queued+' actions';$('#actions .hero h1').textContent=queued+' prepared actions';$('#review .metric:first-child strong').textContent=workspace.people.length+workspace.decisions.length;$('#review .metric:last-child strong').textContent='0';$('#review .metric:last-child .delta').textContent='No live replies';$('.crumb b').textContent=activeRole?.title||'Example workspace';renderList();renderDetail();renderQueue();}
renderDetail=function(){const c=candidates[selected];const panel=$('#candidateDetail');panel.replaceChildren();const heading=document.createElement('h2');heading.textContent=c?.name||'No candidates to review';panel.append(heading);const summary=document.createElement('p');summary.textContent=c?c.summary:'This role has no search results. You can try a clearly labelled example review below.';panel.append(summary);if(c){for(const [label,evidence] of c.reasons){const row=document.createElement('p');row.textContent=label+': '+evidence;panel.append(row);}const note=document.createElement('p');note.textContent='Illustrative profile. Evidence has not been independently verified.';panel.append(note);for(const [label,kind]of [['Pass','pass'],['Approve for outreach','approve']]){const b=document.createElement('button');b.className='btn';b.textContent=label;b.onclick=()=>decide(kind);panel.append(b);}}else{const b=document.createElement('button');b.className='btn';b.textContent='Load example candidates';b.onclick=()=>{workspace.people=structuredClone(samplePeople);workspace.decisions=[];workspace.queue=[];saveWorkspace();renderWorkspace();};panel.append(b);}if(workspace.decisions.length){const undo=document.createElement('button');undo.className='btn';undo.textContent='Undo last decision';undo.onclick=()=>{const d=workspace.decisions.pop();workspace.people.push(d.person);workspace.queue=workspace.queue.filter(q=>q.name!==d.person.name);saveWorkspace();renderWorkspace();};panel.append(undo);}panel.style.padding='24px';};
decide=function(kind){const person=workspace.people.splice(selected,1)[0];if(!person)return;workspace.decisions.push({kind,person});if(kind==='approve'&&!workspace.queue.some(x=>x.name===person.name))workspace.queue.push({...person,draft:'',needsName:person.tags.includes('Name check')});saveWorkspace();renderWorkspace();};
function renderQueue(){const stack=$('.action-stack');stack.replaceChildren();for(const item of workspace.queue){const row=document.createElement('div');row.className='action-card';const name=document.createElement('h3');name.textContent='Invite '+item.name;const b=document.createElement('button');b.className='btn';b.textContent=item.needsName?'Resolve name':'Review';b.onclick=()=>openAction(item.name);row.append(name,b);stack.append(row);}if(!workspace.queue.length)stack.textContent='No pending actions. Approve a candidate first.';$('#actions .hero .btn').onclick=()=>{if(workspace.queue.length)openAction(workspace.queue[0].name);};}
openAction=function(name){openItem=workspace.queue.find(x=>x.name===name);if(!openItem)return;returnFocus=document.activeElement;const modal=$('#actionModal');modal.hidden=false;modal.classList.add('open');$('.app').inert=true;$('#modalTitle').textContent='Review '+name;$('#modalIntro').textContent='Prototype: edit and save this draft, then simulate its completion. No message is sent.';$('#draftText').textContent=openItem.draft||`Hi ${name.split(' ')[0]}, I’m recruiting for ${activeRole?.title||'the example role'}${activeRole?' in '+activeRole.location:''}. Would you be open to a conversation?`;$('#openLinkedIn').textContent='Simulate completion';$('#openLinkedIn').disabled=openItem.needsName;$('#openLinkedIn').style.opacity=openItem.needsName?'.45':'1';$('#modalError').classList.toggle('show',openItem.needsName);let input=$('#confirmedName');if(!input){const label=document.createElement('label');label.textContent='Confirm full name';input=document.createElement('input');input.id='confirmedName';label.htmlFor=input.id;$('#modalError').after(label,input);input.oninput=()=>{const valid=input.value.trim().split(/\s+/).length>=2;$('#openLinkedIn').disabled=!valid;$('#openLinkedIn').style.opacity=valid?'1':'.45';};}input.hidden=!openItem.needsName;input.previousElementSibling.hidden=input.hidden;input.value=openItem.name;$('#actionModal .close').focus();};
closeModal=function(){if(openItem){openItem.draft=$('#draftText').textContent;saveWorkspace();}$('#actionModal').hidden=true;$('#actionModal').classList.remove('open');$('.app').inert=false;openItem=null;returnFocus?.focus();};
completeAction=function(){if(!openItem||$('#openLinkedIn').disabled)return;const item=openItem;closeModal();workspace.queue=workspace.queue.filter(x=>x!==item);saveWorkspace();renderWorkspace();toast('Example action completed. Nothing was sent.');};
$('#actionModal').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const nodes=[...$('#actionModal').querySelectorAll('button,input,[contenteditable]')].filter(n=>!n.disabled&&n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
connectLinkedIn=function(){toast('This hosted prototype cannot connect LinkedIn. Use Log in in the local Sourcer app.');};
function activateWorkspace(role){activeRole=role;loadWorkspace();}
const originalSwitch=switchScreen;
switchScreen=function(id){if(id==='role'&&activeRole){selectSavedRole(activeRole.id);return;}originalSwitch(id);$$('[data-screen]').forEach(b=>b.setAttribute('aria-current',b.dataset.screen===id?'page':'false'));};
$$('[data-screen]').forEach(b=>b.setAttribute('aria-label',b.dataset.screen));$('#toast').setAttribute('role','status');
$$('.query').forEach((q,i)=>{q.setAttribute('aria-label','Example search '+(i+1));const buttons=q.parentElement.querySelectorAll('.search-actions button');buttons[0].onclick=async()=>{try{await navigator.clipboard.writeText(q.textContent);toast('Copied');}catch{toast('Clipboard unavailable. Select and copy the text manually.');}};buttons[1].onclick=()=>q.focus();});
$('#role .hero .btn.primary').onclick=()=>{try{localStorage.setItem('sourcer.example.brief',JSON.stringify({spec:$('.spec-copy').textContent,queries:$$('.query').map(q=>q.textContent)}));toast('Example brief saved in this browser');}catch{toast('Could not save example brief');}};
try{const r=JSON.parse(localStorage.getItem('sourcer.example.brief'));if(r){$('.spec-copy').textContent=r.spec;$$('.query').forEach((q,i)=>q.textContent=r.queries[i]);}}catch{}
const unsupported=['View original','Version history','Try on next search','Settings'];$$('button').filter(b=>unsupported.includes(b.textContent.trim())).forEach(b=>{b.disabled=true;b.title='Not available in this prototype';});
$$('.seg button').forEach((b,i)=>b.onclick=()=>{workspace.people.sort(i?(a,b)=>a.name.localeCompare(b.name):(a,b)=>b.score-a.score);$$('.seg button').forEach(x=>x.classList.toggle('on',x===b));renderWorkspace();});$$('.seg button')[1].textContent='Name';
$('.search').hidden=true;$('.privacy p').textContent='Prototype data is stored in this browser. No LinkedIn actions are performed.';$('.privacy b').textContent='Private prototype';$('.manual span').textContent='This is a simulated completion; no profile is opened or message sent.';
let savedActive;try{savedActive=savedRoles.find(r=>r.id===localStorage.getItem(roleKey+'.active'));}catch{}if(savedActive)activateWorkspace(savedActive);else loadWorkspace();
